
FAIL Signals are not stored in the cache API promise_test: Unhandled rejection with value: object "ReferenceError: Can't find variable: AbortController"
FAIL Signals are not stored in the cache API, even if they're already aborted promise_test: Unhandled rejection with value: object "ReferenceError: Can't find variable: AbortController"

